### ISSUE TITLE
There is a problem with mouse scrolling

### ISSUE THREAD

**Issue by okssq** [HJ29/vue3-scroll-picker#2]
eg: the select optios : [1,2,3,4,5,6,7,8] ,when the options length > 3, There is no way to transition from 1 to 2 when scrolling the mouse, and always jump 2 steps

**Comment by HJ29** [comment]
I think it depends on mouse scroll sensitivity?
i tried with my mouse and laptop touch pad, it doesn't jump 2 steps
i think i will add a parameter to set mouse scroll sensitivity

**Comment by okssq** [comment]
> I think it depends on mouse scroll sensitivity?
> i tried with my mouse and laptop touch pad, it doesn't jump 2 steps
> i think i will add a parameter to set mouse scroll sensitivity

think you very much

**Comment by HJ29** [comment]
v0.1.15 introduce a wheel-speed props.
default value of wheel-speed is 1, make it 0.5 or any value lower than 1, see if it fixed your problem
``` html
  <scroll-picker  
    :wheel-speed="0.5"
  />
```

**Comment by everyPassion** [comment]
> v0.1.15 introduce a wheel-speed props.
> default value of wheel-speed is 1, make it 0.5 or any value lower than 1, see if it fixed your problem
> 
> ```
>   <scroll-picker  
>     :wheel-speed="0.5"
>   />
> ```

thank you very much
