### ISSUE TITLE
style code affect global style

### ISSUE THREAD

**Issue by okssq** [HJ29/vue3-scroll-picker#3]
i find that code  will affect the global style！
> ::-webkit-scrollbar {
>     width: 0;
>     height: 5px
> }
> 
> ::-webkit-scrollbar-thumb {
>     background: rgba(0, 0, 0, .1);
>     border-radius: 10px
> }

can you change your code like that? i coun't!! thank you very much!!!

>  [your use className]::-webkit-scrollbar { }
>  [your use className]::-w-webkit-scrollbar-thumb{ }

**Comment by HJ29** [comment]
v0.1.14 fixed this problem, thanks.

**Comment by everyPassion** [comment]
> v0.1.14 fixed this problem, thanks.

thank you very much
